# Generated by Django 5.1.3 on 2024-12-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.booking'),
            preserve_default=False,
        ),
    ]
